version: '3.8'

networks:
  nextdevice-network:
    external: true

services:
  db:
    image: postgres:15
    restart: always
    container_name: nextdevice-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: nextDevice_database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - nextdevice-network

  backend:
    build: .
    container_name: nextdevice-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - nextdevice-network

volumes:
  pg_data:
